from decimal import Decimal

from config import MAX_TRANSACTIONS_PER_BLOCK as CONFIG_MAX_TRANSACTIONS_PER_BLOCK
from config import MINING_REWARD_AMOUNT as CONFIG_MINING_REWARD_AMOUNT


GENESIS_PREVIOUS_HASH = "0" * 64
GENESIS_BLOCK_ID = 0
GENESIS_DESCRIPTION = "Genesis block"
GENESIS_NONCE = 42
GENESIS_HASH = "003b875e335a9acf04b9c275499e9d5c283520af89558ca3b558c6a37dcc0a30"
MINING_REWARD_AMOUNT = Decimal(str(CONFIG_MINING_REWARD_AMOUNT))
MINING_REWARD_SENDER = "SYSTEM"
MAX_TRANSACTIONS_PER_BLOCK = CONFIG_MAX_TRANSACTIONS_PER_BLOCK
