from decimal import Decimal

from config import MAX_TRANSACTIONS_PER_BLOCK as CONFIG_MAX_TRANSACTIONS_PER_BLOCK
from config import MINING_REWARD_AMOUNT as CONFIG_MINING_REWARD_AMOUNT


GENESIS_PREVIOUS_HASH = "0" * 64
MINING_REWARD_AMOUNT = Decimal(str(CONFIG_MINING_REWARD_AMOUNT))
MINING_REWARD_SENDER = "SYSTEM"
MAX_TRANSACTIONS_PER_BLOCK = CONFIG_MAX_TRANSACTIONS_PER_BLOCK
